version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  jobs:
    install:
      - pip install -r docs/requirements.txt
      - pip install .

    build:
      html:
        - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py